### ISSUE TITLE
Error on second task

### ISSUE THREAD

**Issue by jmeas** [silpion/ansible-maven#1]
Hey there, I got this from role from ansible-galaxy, but I'm encountering an issue when the role runs. The error is:

```sh
TASK: [groover.maven | Install Maven download directory (local)] ************** 
failed: [default] => {"failed": true, "item": "", "parsed": false}
invalid output was: [sudo via ansible, key=yxlbvosgslyqorwbhexokkxeyczgcprc] password: 
```

Do you have any thoughts on what this might be?

My playbook is:

```yaml
-
  hosts: all
  remote_user: vagrant
  sudo: yes
  vars:
    app_base_path: "/vagrant/"
    default_user: "vagrant"
  roles:
    - briancoca.oracle_java7
    - groover.maven
```

**Comment by niyue** [comment]
I ran into the same issue, and I am using this role in my playbook via Vagrant 1.7.2 and Ansible 1.8.4

**Comment by spul** [comment]
Hi,

I'm currently working on a general purpose fix for local download and upload of redistributables.

**Comment by spul** [comment]
Fixed with current release.
